host: httpbin.int.kube
namespacePrefix: service
systemNamespace: ext-authz-token-exchange-e2e

labels:
  partOfKey: app.kubernetes.io/part-of
  partOfValue: ext-authz-token-exchange-e2e

policy:
  labelKey: ext-authz-token-exchange.magneticflux.net/enabled
  labelValue: "true"
  namespaceLabelKey: ext-authz-token-exchange.magneticflux.net/policy
  namespaceLabelValue: enabled
  namespaceSelector: ext-authz-token-exchange.magneticflux.net/policy=enabled
  httpbinResourceBase: https://httpbin.int.kube

fakeTokenEndpoint:
  name: fake-token-endpoint
  image: ghcr.io/michaelw/ext-authz-token-exchange-fake-token-endpoint:latest
  imagePullPolicy: IfNotPresent
  port: 8080
  env: {}
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

teams:
  - color: blue
  - color: yellow
  - color: red
    scenarios:
      - name: error-invalid-target
        scope: errors
        pathPrefix: /anything/error-invalid-target
        tokenPath: /token/invalid-target
      - name: error-invalid-grant
        scope: invalid-grant
        pathPrefix: /anything/error-invalid-grant
        tokenPath: /token/invalid-grant
      - name: error-expired-subject-token
        scope: expired-subject-token
        pathPrefix: /anything/error-expired-subject-token
        tokenPath: /token/expired-subject-token
      - name: error-unauthorized
        scope: unauthorized
        pathPrefix: /anything/error-unauthorized
        tokenPath: /token/unauthorized
      - name: error-forbidden
        scope: forbidden
        pathPrefix: /anything/error-forbidden
        tokenPath: /token/forbidden
      - name: error-malformed
        scope: malformed
        pathPrefix: /anything/error-malformed
        tokenPath: /token/malformed
      - name: denied
        action: deny
        pathPrefix: /anything/denied
        methods: ["*"]
