apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | quote }}
  namespace: {{ .Values.pluginNamespace | quote }}
  labels:
{{ include "keycloak.labels" . | indent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.clientIDKey }}: {{ .Values.clients.exchanger.id | quote }}
  {{ .Values.secret.clientSecretKey }}: {{ .Values.clients.exchanger.secret | quote }}
