apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oauth.secretName | quote }}
  namespace: {{ .Values.systemNamespace | quote }}
  labels:
{{ include "ext-authz-token-exchange-e2e.labels" . | indent 4 }}
type: Opaque
stringData:
  client_id: {{ .Values.oauth.clientID | quote }}
  client_secret: {{ .Values.oauth.clientSecret | quote }}
