apiVersion: v2
type: application
name: ext-authz-token-exchange
description: Envoy Ext AuthZ token exchange plugin
version: 0.3.0
appVersion: 0.3.0
dependencies:
  - name: common.itsumi
    version: 0.5.1
    repository: oci://ghcr.io/michaelw
