apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "ext-authz-token-exchange.fullname" . }}-authz
  namespace: {{ .Values.envoyFilter.namespace | quote }}
spec:
  workloadSelector:
    labels:
{{- if .Values.envoyFilter.workloadSelectorLabelsOverride }}
{{ toYaml .Values.envoyFilter.workloadSelectorLabelsOverride | indent 6 }}
{{- else }}
{{ toYaml .Values.envoyFilter.workloadSelectorLabels | indent 6 }}
{{- end }}
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        # XXX: route-specific matching, not the entire gateway
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ext_authz
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            clear_route_cache: true
            failure_mode_allow: false
            grpc_service:
              envoy_grpc:
                cluster_name: outbound|3001||{{ include "ext-authz-token-exchange.serviceName" . }}.{{ .Release.Namespace }}.svc.cluster.local
              timeout: {{ .Values.envoyFilter.timeout | quote }}
