{{- if .Values.oauth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oauth.secretName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "ext-authz-token-exchange.labels" . | indent 4 }}
type: Opaque
stringData:
  {{ .Values.oauth.existingSecret.clientIDKey }}: {{ .Values.oauth.clientID | quote }}
  {{ .Values.oauth.existingSecret.clientSecretKey }}: {{ .Values.oauth.clientSecret | quote }}
{{- end }}
